# Generated by Django 5.0.6 on 2024-06-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Cuit',
            new_name='cuit',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='RazonSocial',
            new_name='razonSocial',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Ubicacion_id',
            new_name='ubicacion_id',
        ),
    ]
