# Generated by Django 5.0.6 on 2024-06-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_cuit_cliente_cuit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatarCliente/'),
        ),
    ]
