# Generated by Django 5.0.6 on 2024-05-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.DecimalField(decimal_places=2, max_digits=20, unique=True)),
                ('Cliente', models.CharField(max_length=100)),
                ('Proyecto', models.CharField(blank=True, max_length=100, null=True)),
                ('FechaEmicion', models.DateField()),
                ('FechaVencimiento', models.DateField(blank=True, null=True)),
                ('Moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('Monto', models.FloatField()),
                ('Detalle', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Referencia', models.DecimalField(decimal_places=2, max_digits=50, unique=True)),
                ('FechaEmicion', models.DateField()),
                ('FechaVencimiento', models.DateField(blank=True, null=True)),
                ('Moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('Monto', models.FloatField()),
                ('Detalle', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos',
            },
        ),
    ]
