# Generated by Django 5.0.6 on 2024-05-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Referencia', models.DecimalField(decimal_places=2, max_digits=50, unique=True)),
                ('FechaEmision', models.DateField()),
                ('FechaVencimiento', models.DateField(blank=True, null=True)),
                ('Moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('Monto', models.FloatField()),
                ('Detalle', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'gastos',
            },
        ),
        migrations.DeleteModel(
            name='Gastos',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='FechaEmicion',
            new_name='FechaEmision',
        ),
    ]
