# Generated by Django 5.0.6 on 2024-05-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_factura_moneda'),
        ('proyectos', '0003_proyecto_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Moneda',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.RemoveField(
            model_name='factura',
            name='Proyecto',
        ),
        migrations.AddField(
            model_name='factura',
            name='Proyecto',
            field=models.ManyToManyField(blank=True, null=True, related_name='factura_proyecto', to='proyectos.proyecto'),
        ),
    ]
