# Generated by Django 5.0.6 on 2024-06-01 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_factura_moneda_remove_factura_proyecto_and_more'),
        ('proyectos', '0003_proyecto_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='Proyecto',
        ),
        migrations.AddField(
            model_name='factura',
            name='Proyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='factura_proyecto', to='proyectos.proyecto'),
        ),
    ]
