# Generated by Django 5.0.6 on 2024-06-01 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_remove_factura_proyecto_factura_proyecto'),
        ('proyectos', '0003_proyecto_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto_Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proyecto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='factura_proyecto', to='proyectos.proyecto')),
            ],
        ),
        migrations.AlterField(
            model_name='factura',
            name='Proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.proyecto_factura'),
        ),
    ]
