# Generated by Django 5.0.6 on 2024-06-01 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_rename_proyecto_proyecto_factura_proyecto_facturado'),
        ('proyectos', '0003_proyecto_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto_factura',
            name='Proyecto_facturado',
        ),
        migrations.AddField(
            model_name='proyecto_factura',
            name='Proy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='factura_proyecto_fact', to='proyectos.proyecto'),
        ),
    ]
