# Generated by Django 5.0.6 on 2024-06-01 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_remove_proyecto_factura_proyecto_facturado_and_more'),
        ('proyectos', '0003_proyecto_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto_factura',
            name='Proy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proyecto_factura_proyecto', to='proyectos.proyecto'),
        ),
    ]
