# Generated by Django 5.0.6 on 2024-06-01 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_alter_proyecto_factura_proy'),
        ('proyectos', '0003_proyecto_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Proyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='factura_proyecto', to='proyectos.proyecto'),
        ),
        migrations.DeleteModel(
            name='Proyecto_Factura',
        ),
    ]
