# Generated by Django 5.0.6 on 2024-06-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_alter_factura_proyecto_delete_proyecto_factura'),
        ('proyectos', '0003_proyecto_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='Proyecto',
        ),
        migrations.AddField(
            model_name='factura',
            name='Proyecto',
            field=models.ManyToManyField(to='proyectos.proyecto'),
        ),
    ]
