# Generated by Django 5.0.6 on 2024-06-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_remove_factura_proyecto_factura_proyecto'),
        ('proyectos', '0003_proyecto_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Proyecto',
            field=models.ManyToManyField(blank=True, null=True, to='proyectos.proyecto'),
        ),
    ]
