# Generated by Django 5.0.6 on 2024-05-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Pais', models.CharField(blank=True, max_length=100, null=True)),
                ('FechaInicio', models.DateField()),
                ('FechaFin', models.DateField()),
                ('Estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
            },
        ),
    ]
