# Generated by Django 5.0.6 on 2024-05-31 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('proyectos', '0002_alter_proyecto_fechafin'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='Cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proyecto_cliente', to='clientes.cliente'),
        ),
    ]
