# Generated by Django 5.0.6 on 2024-06-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyecto_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='Cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='Estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='FechaFin',
            new_name='fechaFin',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='FechaInicio',
            new_name='fechaInicio',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='Pais',
            new_name='pais',
        ),
    ]
