# Generated by Django 5.0.6 on 2024-05-31 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_personal_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='usuario',
            new_name='Usuario',
        ),
    ]
