# Generated by Django 5.0.6 on 2024-06-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_personal_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
    ]
