# Generated by Django 5.0.6 on 2024-06-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_alter_personal_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='pais',
            new_name='sede',
        ),
        migrations.AlterField(
            model_name='personal',
            name='Apellido',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
